version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
